### PR TITLE
Add Contributing Guide

### LINKED ISSUE #156: Contributing Guide
We should have a contributing guide. I'm not sure that we'll need it right away, but I'd like to make sure that nobody is turned away because we don't have one, event if it's a simple one.

### PR DESCRIPTION
**Pull request by felixrieseberg**
Closes #156
- Adds CONTRIBUTING.md with details
- Moved development instructions into the guide
- Updated Readme

### CODE REVIEW

**Comment by sedouard** [comment]
Although we will have a CLA bot, you should add a section similar to the [legal section of the touch develop project](https://github.com/Microsoft/TouchDevelop/blob/master/CONTRIBUTING.md)

**Comment by sedouard** [comment]
You should mention new features should come with unit tests

**Comment by felixrieseberg** [comment]
Good point - added.

**Comment by sedouard** [comment]
How bout mentioning PR Workflow?
-Fork the Repo
-Topic Branch
-Commit (using the mentioned commit format)
-PR
-Collaborator Approval

**Comment by felixrieseberg** [comment]
Good point - added.

**Comment by felixrieseberg** [comment]
I left it as it is (let's not get crazy here - this is a tiny app with currently less than a hundred users), but feel free to add more if you think it's necessary.

**Pull request merged**
